version: '3.8'

services:
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2xPqPfmfy4FvPh80PQhUZ3tAoOI_4B7J3TZxpCzGTjaXt6iBm
    command: http host.docker.internal:30000
    network_mode: host
